# DataSource Config
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-p0taec8i.sql.tencentcdb.com:28503/db_proj
    username: root
    password: Rootroot651
mybatis-plus:
  typeEnumsPackage: com.db.herviz.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #���sql��־
#  mapper-locations: classpath*:mapper/**Mapper.xml